#!/usr/bin/env node
/**
 * STYLE-DRIVEN MOVESETS FOR THE WHOLE ROSTER.
 *
 * Replaces the seeded draw that `map_commands.mjs --full` used to do. The clip
 * for each of the 26 directional slots, and the gameplay data attached to it,
 * now come from the fighter's canon style profile
 * (src/engine/combat/FighterStyleProfiles.ts) over the measured strike pool
 * (src/engine/combat/StrikeClipPool.ts). No random or hash seed is involved.
 *
 *   node --experimental-strip-types tools/moves/build_style_movesets.mjs           report
 *   node --experimental-strip-types tools/moves/build_style_movesets.mjs --write   write
 *        public/motion/movesets.json            (26 generated slots per fighter)
 *        src/generated/RosterStyleClips.generated.ts (neutral LP/RP/LK/RK/crouch clip per fighter)
 *   then: node scripts/pack-motion-zstd.mjs     (refresh the .zst the runtime fetches)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { buildStrikeClipPool } from '../../src/engine/combat/StrikeClipPool.ts';
import {
  buildStyledMoveset, resolveStyle, styleRepertoire, pickStyleClip, FIGHTER_STYLE_TABLE, newRosterDiversity,
} from '../../src/engine/combat/FighterStyleProfiles.ts';
import { BANNON_ROSTER } from '../../src/data/bannonRoster.ts';

const idx = JSON.parse(readFileSync('public/motion/baked/index.json', 'utf8'));
const bodies = existsSync('public/motion/clip-bodies.json') ? JSON.parse(readFileSync('public/motion/clip-bodies.json', 'utf8')) : {};
const { pool, rejected } = buildStrikeClipPool(idx, bodies);
const poolNames = new Set(pool.map((c) => c.name));

const sets = {};
const neutral = {};
const missingSignature = {};
const diversity = newRosterDiversity();
for (const f of BANNON_ROSTER) {
  const style = resolveStyle(f.id, { speed: f.speed, strength: f.strength });
  if (!style) { console.warn(`no style profile for ${f.id} — skipped (UNKNOWN, not defaulted)`); continue; }
  missingSignature[f.id] = style.signatureClips.filter((c) => !poolNames.has(c));
  sets[f.id] = buildStyledMoveset(style, pool, diversity);
  // NEUTRAL SLOTS: the engine's base LP/RP/LK/RK and down+button. Same
  // style-driven picker, its own usage counter so neutral is not starved.
  const rep = styleRepertoire(style, pool, 7, diversity);
  const used = new Map();
  const pick = (kick, height, stance, tempo) => {
    const c = pickStyleClip(style, pool, { kick, height, stance, tempo }, used, rep);
    if (c) used.set(c.name, (used.get(c.name) ?? 0) + 1);
    return c?.name ?? null;
  };
  neutral[f.id] = {
    lightAttack: pick(false, 'mid', 'Ground', 'light'),
    heavyAttack: pick(false, 'mid', 'Ground', 'heavy'),
    lowKick: pick(true, 'mid', 'Ground', 'light'),
    highKick: pick(true, 'high', 'Ground', 'heavy'),
    crouchLight: pick(false, 'low', 'Crouch', 'light'),
    crouchKick: pick(true, 'low', 'Crouch', 'heavy'),
  };
}
const unprofiled = Object.keys(FIGHTER_STYLE_TABLE).filter((id) => !BANNON_ROSTER.some((f) => f.id === id));

if (process.argv.includes('--write')) {
  writeFileSync('public/motion/movesets.json', JSON.stringify(sets));
  const ts = `// GENERATED by tools/moves/build_style_movesets.mjs — do not edit by hand.
// Neutral-slot clips per fighter, chosen by FighterStyleProfiles over the
// measured strike pool (${pool.length} clips). A null entry is MISSING_CLIP:
// the fighter keeps the semantic slot animation and the audit says so.
export const ROSTER_STYLE_CLIPS: Record<string, Record<'lightAttack' | 'heavyAttack' | 'lowKick' | 'highKick' | 'crouchLight' | 'crouchKick', string | null>> = ${JSON.stringify(neutral, null, 2)};
`;
  writeFileSync('src/generated/RosterStyleClips.generated.ts', ts);
  console.log('wrote public/motion/movesets.json and src/generated/RosterStyleClips.generated.ts');
}

const rej = {};
for (const r of Object.values(rejected)) rej[r] = (rej[r] ?? 0) + 1;
console.log(`strike pool: ${pool.length} clips (${pool.filter((c) => c.admittedBy !== 'attack').length} admitted by widening: ${pool.filter((c) => c.admittedBy !== 'attack').map((c) => `${c.name}[${c.admittedBy}]`).join(', ')})`);
console.log('pool rejections:', JSON.stringify(rej));
const famOf = new Map(pool.map((c) => [c.name, c.family ?? 'bank']));
const famCount = {};
for (const c of pool) famCount[c.family ?? 'bank'] = (famCount[c.family ?? 'bank'] ?? 0) + 1;
console.log('pool families:', JSON.stringify(famCount));
const perFighterFamilies = {};
for (const [id, moves] of Object.entries(sets)) {
  const f = {};
  for (const m of moves) { const k = famOf.get(m.clip) ?? 'bank'; f[k] = (f[k] ?? 0) + 1; }
  for (const c of Object.values(neutral[id] ?? {})) if (c) { const k = famOf.get(c) ?? 'bank'; f[k] = (f[k] ?? 0) + 1; }
  perFighterFamilies[id] = f;
}
if (process.argv.includes('--families')) for (const [id, f] of Object.entries(perFighterFamilies)) console.log(id.padEnd(16), JSON.stringify(f));
if (process.argv.includes('--write')) writeFileSync('tools/moves/roster-clip-families.json', JSON.stringify(perFighterFamilies, null, 1) + '\n');
console.log('fighters:', Object.keys(sets).length, 'unprofiled table entries:', unprofiled);
console.log('signature clips missing from pool (MISSING_CLIP):', JSON.stringify(Object.fromEntries(Object.entries(missingSignature).filter(([, v]) => v.length))));
