// GENERATED by scripts/retarget/gen-canonical-rest.mjs from public/models/BANNON_rigged.glb — do not edit.
/** Rest local rotation [x, y, z, w] of each humanoid-mapped canonical joint (sanitized names). */
export const CANONICAL_REST_LOCAL: Readonly<Record<string, readonly [number, number, number, number]>> = {
  "mixamorigLeftHand": [
    0.095804,
    0.05219,
    -0.017645,
    0.993874
  ],
  "mixamorigLeftFoot": [
    0.091526,
    0.548358,
    -0.478733,
    0.679515
  ],
  "mixamorigLeftToeBase": [
    0,
    0,
    0,
    1
  ],
  "mixamorigRightHand": [
    -0.035291,
    0.040689,
    -0.062073,
    0.996617
  ],
  "mixamorigRightFoot": [
    0.244584,
    0.32342,
    -0.441097,
    0.800632
  ],
  "mixamorigRightToeBase": [
    0,
    0,
    0,
    1
  ],
  "mixamorigHead": [
    0,
    0,
    0,
    1
  ],
  "mixamorigLeftForeArm": [
    0.182014,
    0.176171,
    -0.09726,
    0.962484
  ],
  "mixamorigLeftArm": [
    0.26925,
    0,
    0,
    0.96307
  ],
  "mixamorigLeftShoulder": [
    0.849396,
    -0.08536,
    0.02015,
    0.520417
  ],
  "mixamorigLeftLeg": [
    0.014723,
    -0.156117,
    0.129285,
    0.97913
  ],
  "mixamorigLeftUpLeg": [
    0.992405,
    0.051955,
    0.051955,
    0.098659
  ],
  "mixamorigRightForeArm": [
    -0.150808,
    0.077774,
    -0.140874,
    0.975378
  ],
  "mixamorigRightArm": [
    -0.269249,
    0,
    0,
    0.963071
  ],
  "mixamorigRightShoulder": [
    -0.845337,
    0.020151,
    -0.08536,
    0.526985
  ],
  "mixamorigRightLeg": [
    -0.003874,
    -0.111862,
    0.137429,
    0.984167
  ],
  "mixamorigRightUpLeg": [
    -0.992861,
    -0.042368,
    -0.042368,
    0.10314
  ],
  "mixamorigHips": [
    0,
    0,
    0,
    1
  ],
  "mixamorigSpine": [
    -0.001271,
    0.035624,
    0.035624,
    0.998729
  ],
  "mixamorigSpine1": [
    -0.00259,
    0.026511,
    0.026394,
    0.999297
  ],
  "mixamorigSpine2": [
    0,
    0,
    0,
    1
  ],
  "mixamorigNeck": [
    -0.017226,
    -0.201966,
    -0.205691,
    0.957394
  ]
};
