#!/usr/bin/env node
/**
 * HOW LONG DID EACH THING ACTUALLY TAKE?
 *
 * Owner: "we need to measure how long it takes to fix each problem as we go …
 * so we can measure our own efficiency, how efficient and optimized we get …
 * every session we get actual progress done on a big scale instead of this
 * really micro scale stuff."
 *
 * A hand-written log drifts from the truth the moment it is convenient to let
 * it. So the dates here are READ FROM GIT: docs/owner-reports.json says what he
 * reported and which commit fixed it, and every duration is derived from that
 * commit's real author date. Nothing about elapsed time is typed in by hand.
 *
 * Usage: node tools/log/timeline.mjs [--write]
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const REPORTS = 'docs/owner-reports.json';
const OUT = 'docs/WORK_LOG.md';

function commitDate(sha) {
  try {
    return new Date(execFileSync('git', ['show', '-s', '--format=%aI', sha], { encoding: 'utf8' }).trim());
  } catch {
    return null;
  }
}

const { reports } = JSON.parse(readFileSync(REPORTS, 'utf8'));
const DAY = 86400000;

const rows = reports.map((r) => {
  const fixedAt = r.fixed ? commitDate(r.fixed) : null;
  const reportedAt = new Date(`${r.reported}T00:00:00Z`);
  const days = fixedAt ? (fixedAt - reportedAt) / DAY : (Date.now() - reportedAt) / DAY;
  return { ...r, fixedAt, reportedAt, days, open: !r.fixed };
});

const fmt = (d) => (d < 1 ? `${Math.max(0, Math.round(d * 24))}h` : `${d.toFixed(1)}d`);

const open = rows.filter((r) => r.open);
const closed = rows.filter((r) => !r.open && r.fixedAt);
const median = closed.length
  ? [...closed].sort((a, b) => a.days - b.days)[Math.floor(closed.length / 2)].days
  : null;

const lines = [];
lines.push('# WORK LOG — what was reported, and how long it took');
lines.push('');
lines.push('Generated by `node tools/log/timeline.mjs --write` from `docs/owner-reports.json`.');
lines.push('Every duration is derived from the fixing commit\'s real author date in git, so it');
lines.push('cannot drift from what happened. Symptoms are the owner\'s own words.');
lines.push('');
lines.push(`**${closed.length} closed, ${open.length} open.**`
  + (median === null ? '' : ` Median time to fix: **${fmt(median)}**.`));
lines.push('');
lines.push('| reported | status | took | what he said |');
lines.push('|---|---|---|---|');
for (const r of [...rows].sort((a, b) => b.reportedAt - a.reportedAt)) {
  const said = r.symptom.replace(/\|/g, '\\|').slice(0, 90);
  lines.push(`| ${r.reported} | ${r.open ? '**OPEN**' : r.fixed} | ${fmt(r.days)} | ${said}… |`);
}
lines.push('');
for (const r of rows) {
  lines.push(`## ${r.id} — ${r.open ? `OPEN, ${fmt(r.days)} old` : `fixed in \`${r.fixed}\` after ${fmt(r.days)}`}`);
  lines.push('');
  lines.push(`> ${r.symptom}`);
  lines.push('');
  lines.push(`**Cause.** ${r.rootCause}`);
  if (r.attempted) lines.push(`\n**Tried and reverted.** ${r.attempted}`);
  if (r.howFound) lines.push(`\n**Found by.** ${r.howFound}`);
  if (r.lesson) lines.push(`\n**Lesson.** ${r.lesson}`);
  lines.push('');
}

const text = lines.join('\n');
if (process.argv.includes('--write')) {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT}`);
} else {
  console.log(text);
}
